### ISSUE TITLE
Anti-Virus Detection

### ISSUE THREAD

**Issue by entyav** [entynetproject/proton#2]
So, @enty8080, I love your work, but WTF?
When I am trying to get `system.ini` file using your `implant/util/download_file` payload, it's returning me this error. I will move `stager/js/mshta` to RAM.

```
[proton: ZOMBIE 0 (10.0.2.15) - C:\Windows]> download system.ini
[*] Zombie 0: Job 11 (implant/util/download_file) created.
[+] Zombie 0: Job 11 (implant/util/download_file) completed.
[+] File C:\Windows\system.ini saved to /tmp/system.ini (219 bytes).
[!] Zombie 0: Timed out. 
```

**Comment by enty8080** [comment]
This is actual subject to talk, ya?

**Comment by enty8080** [comment]
We FIXED THIS!!!
